CREATE TABLE USUARIOS(
                         idusuario NUMBER(18) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                         nome VARCHAR2(255),
                         email VARCHAR2(255),
                         senha VARCHAR2(255),

                         PRIMARY KEY (idusuario)
)
    /

CREATE TABLE TAREFAS(
                        idtarefa     NUMBER(18) generated by default on null as identity,
                        idusuario    NUMBER(18),
                        prioridade   VARCHAR2(100),
                        descricao    VARCHAR2(4000),
                        dtatarefa    DATE,
                        concluida    INTEGER,
                        dtaconcluida DATE,
                        dtainsert    DATE,
                        dtaupdate    DATE,

                        PRIMARY KEY (idtarefa),
                        FOREIGN KEY(idusuario) REFERENCES USUARIOS(idusuario)
)